# Generated by Django for netbox_azure_groups plugin

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0002_squashed_0059'),
        ('netbox_azure_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=None)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'tenancy'), ('model', 'contact')), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='netbox_azure_groups.azuregroup')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Group Ownership',
                'verbose_name_plural': 'Group Ownerships',
                'ordering': ['group__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='groupownership',
            constraint=models.UniqueConstraint(fields=('group', 'content_type', 'object_id'), name='unique_group_ownership'),
        ),
    ]