# Generated by Django 5.1.3 on 2025-08-28 13:10

import django.contrib.postgres.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_azure_groups', '0004_refactor_to_direct_foreignkeys'),
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactgroupmembership',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contactgroupmembership',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='contactgroupownership',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contactgroupownership',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='devicegroupmembership',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='devicegroupmembership',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags'),
        ),
    ]