# Generated by Django for netbox-azure-groups

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0014_contact_link'),
        ('netbox_azure_groups', '0010_add_business_unit_and_update_protected_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnitMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('role', models.CharField(choices=[('member', 'Member'), ('manager', 'Manager'), ('admin', 'Administrator'), ('contributor', 'Contributor'), ('viewer', 'Viewer')], default='member', help_text='Role of the contact within this business unit', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='When membership started', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When membership ends/ended', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether membership is currently active')),
                ('notes', models.TextField(blank=True, help_text='Notes about this membership')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='netbox_azure_groups.businessunit')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_unit_memberships', to='tenancy.contact')),
            ],
            options={
                'verbose_name': 'Business Unit Membership',
                'verbose_name_plural': 'Business Unit Memberships',
                'ordering': ['business_unit', 'role', 'contact'],
            },
        ),
        migrations.AddIndex(
            model_name='businessunitmembership',
            index=models.Index(fields=['business_unit', 'is_active'], name='netbox_azur_busines_b6c97a_idx'),
        ),
        migrations.AddIndex(
            model_name='businessunitmembership',
            index=models.Index(fields=['contact', 'is_active'], name='netbox_azur_contact_dd7b1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businessunitmembership',
            unique_together={('business_unit', 'contact')},
        ),
    ]